using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
// do not document in help
namespace SierraOS.Commands
{
    public class Strobe : Command
    {
        public Strobe(string name) : base(name) { }

        public override string execute(string[] args)
        {
            StrobeScreen();
            return "";

        }

        public void StrobeScreen()
        {
            Console.WriteLine("Epilepsy warning!");
            Thread.Sleep(4000);
            Console.Clear();
            Console.BackgroundColor = ConsoleColor.Black;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.White;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Blue;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Red;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Green;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Yellow;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Cyan;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Gray;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Black;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.White;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Blue;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Red;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Green;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Yellow;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Cyan;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Gray;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Black;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.White;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Blue;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Red;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Green;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Yellow;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Cyan;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Gray;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Black;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.White;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Blue;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Red;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Green;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Yellow;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Cyan;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Gray;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Black;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.White;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Blue;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Red;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Green;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Yellow;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Cyan;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Gray;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Black;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.White;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Blue;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Red;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Green;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Yellow;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Cyan;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Gray;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Black;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.White;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Blue;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Red;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Green;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Yellow;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Cyan;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Gray;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Black;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.White;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Blue;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Red;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Green;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Yellow;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Cyan;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Gray;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Black;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.White;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Blue;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Red;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Green;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Yellow;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Cyan;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Gray;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Black;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.White;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Blue;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Red;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Green;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Yellow;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Cyan;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Gray;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Black;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.White;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Blue;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Red;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Green;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Yellow;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Cyan;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Gray;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Black;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.White;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Blue;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Red;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Green;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Yellow;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Cyan;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Gray;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Black;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.White;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Blue;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Red;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Green;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Yellow;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Cyan;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Gray;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Black;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.White;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Blue;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Red;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Green;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Yellow;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Cyan;
            Console.Clear();
            Thread.Sleep(50);
            Console.BackgroundColor = ConsoleColor.Gray;
            Console.Clear();
            Thread.Sleep(50);
            Console.ResetColor();
            Console.Clear();
            Console.Beep();
        }
    }
}
